export default {
  tshirt: require('../assets/tshirt.png'),
  shoes: require('../assets/shoes.png'),
  hoodie: require('../assets/hoodie.png'),
  accessory: require('../assets/accessory.png'),
  account: require('../assets/account.png'),
  settings: require('../assets/settings.png'),
  sub_menu: require('../assets/sub_menu.png'),
  dress: require('../assets/dress.png'),
  cap: require('../assets/cap.png'),
  shoes_woman: require('../assets/shoes_woman.png'),
  next: require('../assets/next.png'),
  delete: require('../assets/delete.png'),
  arrow: require('../assets/arrow.png'),
  hatwoman: require('../assets/hatwoman.png'),
  coatman: require('../assets/coatman.png'),
  shirtman: require('../assets/shirtman.png'),
  shirtwoman: require('../assets/shirtwoman.png'),
  adjust: require('../assets/adjust.png'),
  tshirt1: require('../assets/tshirt1.png'),
  tshirt2: require('../assets/tshirt2.png'),
  cancel: require('../assets/cancel.png'),
};
